language: node_js
sudo: required

node_js:
    - "10"

cache:
  directories:
    - node_modules
install:
    - npm install -g vuepress
script:
    - npm run docs:build
deploy:
  provider: pages
  target_branch: gh-pages
  fqdn: shortcuts.save1s.com
  local_dir: docs/.vuepress/dist
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master